config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get    'pages/contact'
  get    'pages/about'

  resources :users

  resources :memberships
  resources :courses
  resources :merchandises
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/membership.rb
class Membership < ApplicationRecord
end

app/models/merchandise.rb
class Merchandise < ApplicationRecord
  has_one_attached :photo

  scope :by_price, -> { order(:price) }
  scope :by_name, -> { order(:name) }
  scope :below_price, ->(price) { where(price: 0...price) }
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password photo first_name last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email password photo first_name last_name])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]
  before_action :admin?, only: %i[new create edit update destroy]

  def index
    @courses = Course.all
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    @course.save

    redirect_to course_path(@course)
  end

  def edit
  end

  def update
    @course.update(course_params)

    redirect_to course_path(@course)
  end

  def destroy
    @course.destroy

    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course).permit(:name, :description)
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def admin?
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[show edit update destroy]
  before_action :admin?, only: %i[new create edit update destroy]

  def index
    @memberships = Membership.all
  end

  def show
  end

  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.new(membership_params)
    @membership.save

    redirect_to membership_path(@membership)
  end

  def edit
  end

  def update
    @membership.update(membership_params)

    redirect_to membership_path(@membership)
  end

  def destroy
    @membership.destroy

    redirect_to memberships_path
  end

  private

  def membership_params
    params.require(:membership).permit(:name, :description, :price)
  end

  def set_membership
    @membership = Membership.find(params[:id])
  end

  def admin?
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/merchandises_controller.rb
class MerchandisesController < ApplicationController
  before_action :set_merchandise, only: %i[show edit update destroy]
  before_action :admin?, only: %i[new create edit update destroy]

  def index
    @merchandises = Merchandise.all
  end

  def show
  end

  def new
    @merchandise = Merchandise.new
  end

  def create
    @merchandise = Merchandise.new(merchandise_params)
    @merchandise.save

    redirect_to merchandise_path(@merchandise)
  end

  def edit
  end

  def update
    @merchandise.update(merchandise_params)

    redirect_to merchandise_path(@merchandise)
  end

  def destroy
    @merchandise.destroy

    redirect_to merchandises_path
  end

  private

  def merchandise_params
    params.require(:merchandise).permit(:name, :description, :price)
  end

  def set_merchandise
    @merchandise = Merchandise.find(params[:id])
  end

  def admin?
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home about contact]

  def home; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def show
    redirect_to root_path unless current_user.admin? || current_user == @user
  end

  def index
    @users = User.all
    redirect_to root_path unless current_user.admin?
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :photo, :first_name, :last_name, :adress, :gender, :phone, :birthday, :city, :state, :zip)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/courses/edit.html.erb
<%= render 'form', membership: @membership %>

app/views/courses/index.html.erb
<div class="row" style="padding:20px;">
  <% @courses.each do |course| %>
    <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to course.name, course_path(course) %></h5>
            <p class="card-text"><%= course.description %></p>
            <a href="#" class="btn btn-primary">button</a>
          </div>
        </div>
    </div>
  <% end %>
</div>

<% if current_user.admin %>
  <%= link_to "create Class", new_course_path  %>
<% end %>

app/views/courses/new.html.erb
<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<h2><%= @course.name %></h2>
<p><%= @course.description %></p>

<% if current_user.admin %>
  <%= link_to 'Edit', edit_course_path(@course) %>
  <%= link_to "Delete", course_path(@course), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tonys Gym</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path("https://tonys-gym.square.site/uploads/b/105d58e0-4a6b-11e9-a2ed-91e638bc6c90/8969B1FE-160D-4A18-BAD5-8488EB486B77.jpeg") %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/memberships/_form.html.erb
<%= simple_form_for(@membership) do |f| %>
  <%= f.input :name, maxlength: 15, label: "Length of Membership", hint: 'maximum length: 15' %>
  <%= f.input :description, label: "Description of Membership" %>
  <%= f.input :price, :collection => [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], label: "Price per month" %>
  <%= f.submit %>
<% end %>

app/views/memberships/index.html.erb
<div class="row" style="padding:20px;">
  <% @memberships.each do |membership| %>
    <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to membership.name, membership_path(membership) %></h5>
            <p class="card-text"><%= membership.description %></p>
            <a href="#" class="btn btn-primary">$<%= membership.price %></a>
          </div>
        </div>
    </div>
  <% end %>
</div>


<% if current_user.admin %>
  <%= link_to "create membership", new_membership_path  %>
<% end %>

app/views/memberships/new.html.erb
<%= render 'form', membership: @membership %>

app/views/memberships/show.html.erb
<h2><%= @membership.name %></h2>
<p><%= @membership.description %></p>
<p><%= @membership.price %></p>

<% if current_user.admin %>
  <%= link_to 'Edit', edit_membership_path(@membership) %>
  <%= link_to "Delete", membership_path(@membership), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

app/views/merchandises/_form.html.erb
<%= simple_form_for(@merchandise) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.submit %>
<% end %>

app/views/merchandises/edit.html.erb
<%= render 'form', merchandise: @merchandise %>

app/views/merchandises/index.html.erb
<div class="row" style="padding:20px;">
  <% @merchandises.each do |merchandise| %>
    <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to merchandise.name, merchandise_path(merchandise) %></h5>
            <p class="card-text"><%= merchandise.description %></p>
            <a href="#" class="btn btn-primary">$<%= merchandise.price %></a>
          </div>
        </div>
    </div>
  <% end %>
</div>

<% if current_user.admin %>
  <%= link_to "create merchandise", new_merchandise_path  %>
<% end %>

app/views/merchandises/new.html.erb
<%= render 'form', merchandise: @merchandise %>

app/views/merchandises/show.html.erb
<h2><%= @merchandise.name %></h2>
<p><%= @merchandise.description %></p>
<p><%= @merchandise.price %></p>

<% if current_user.admin %>
  <%= link_to 'Edit', edit_merchandise_path(@merchandise) %>
  <%= link_to "Delete", merchandise_path(@merchandise), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>

app/views/pages/about.html.erb
<h1>about page</h1>

app/views/pages/contact.html.erb
<h1>contact page</h1>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Tonys Gym</h1>
    <p>Start working out today!</p>
    <a class="btn btn-flat" href="#">Sign Up</a>
  </div>
</div>
<br>
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/3916766/pexels-photo-3916766.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500)">
    Gym Memberships
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/236128/pexels-photo-236128.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)">
    Workout Classes
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)">
    Gym Merchandise
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart"></i> by Nasser Atiyeh
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://tonys-gym.square.site/uploads/b/105d58e0-4a6b-11e9-a2ed-91e638bc6c90/8969B1FE-160D-4A18-BAD5-8488EB486B77.jpeg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Memberships", memberships_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Classes", courses_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Merchandise", merchandises_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :adress %>
  <%= f.input :gender %>
  <%= f.input :birthday %>
  <%= f.input :phone %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zip %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, "Submit Changes", class:'btn btn-primary form-actions mx-auto', style:'width:200px;' %>
<% end %>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.email, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="container alumnus d-lg-flex">
  <div class="alumnus-info-card pb-3">
    <div class="alumnus-info-card-header">
      <%= link_to edit_user_path(@user), class:'alumnus-edit' do %>
        <i class="far fa-edit"></i>
      <% end %>
      <%= cl_image_tag @user.photo.key, class: 'rounded-circle alumnus-avatar' %>
      <br>
      <h1 class="mb-0"><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h1>
      <h4 class="mt-2 mb-0"><%= @user.email %></h4>
      <img class="header-background" src="https://d26jy9fbi4q9wx.cloudfront.net/assets/alumni-bg-256121dc263a7c2657d1bf8fd1e6216b3fff9a34b4b99641d8b78338a1751b6e.svg">
    </div>
    <div class="alumnus-info-card-content">
      <hr>
      <h4>Address</h4>
      <%= @user.adress %>
      <br>
      <%= @user.city %>
      <%= @user.state %>,
      <%= @user.zip %>
      <hr>
      <h4>About Me</h4>
      <%= @user.birthday %>
      <br>
      <%= @user.gender %>
      <br>
      <%= @user.phone %>
      <% if current_user.admin %>
        <%= link_to "All Users", users_path %>
      <% end %>
    </div>
  </div>
  <div class="alumnus-panel">
    <div class="alumnus-panel-content">
      <div class="d-flex justify-content-between align-items-center">
        <h3 class="mt-2">Membership Status</h3>
      </div>
      <div class="alumnus-experiences">
        <p>my membership</p>
      </div>
      <hr>
      <div class="d-flex justify-content-between align-items-center">
        <h3 class="mt-2">Upcoming Classes</h3>
      </div>
      <div class="alumnus-experiences">
        <p>my classes</p>
      </div>
      <hr>
      <div class="d-flex justify-content-between align-items-center">
        <h3 class="mt-2">Previous Orders</h3>
      </div>
      <div class="alumnus-experiences">
        <p>my orders</p>
      </div>
    </div>
  </div>
</div>